#!/bin/bash
# run-all-browser-tests.sh
# Master test runner for browser testing with Chrome DevTools MCP
# MUST be run with Chrome DevTools MCP available

set -e

LIVE_URL="${1:-https://example.netlify.app}"
VIEWPORT_WIDTH=375
VIEWPORT_HEIGHT=667
DEVICE="iPhone SE"

echo "======================================"
echo "  BROWSER TESTING: $LIVE_URL"
echo "  Viewport: ${VIEWPORT_WIDTH}x${VIEWPORT_HEIGHT} ($DEVICE)"
echo "======================================"
echo ""
echo "⚠️  This script requires Chrome DevTools MCP to be active."
echo "    Claude will use mcp__chrome-devtools__* tools for testing."
echo ""

PASSED=0
FAILED=0
RESULTS=()

# Helper function to record result
record_result() {
    local test_name="$1"
    local status="$2"
    local details="$3"

    if [[ "$status" == "PASS" ]]; then
        ((PASSED++))
        RESULTS+=("✅ $test_name")
    else
        ((FAILED++))
        RESULTS+=("❌ $test_name: $details")
    fi
}

echo "======================================"
echo "  TEST CHECKLIST FOR CLAUDE"
echo "======================================"
echo ""
echo "Claude should execute these tests using Chrome DevTools MCP:"
echo ""
echo "1. NAVIGATE & RESIZE"
echo "   - Navigate to: $LIVE_URL"
echo "   - Resize page to: ${VIEWPORT_WIDTH}x${VIEWPORT_HEIGHT}"
echo "   - Take screenshot"
echo ""
echo "2. PAGE LOAD TEST"
echo "   - Verify page loads within 5 seconds"
echo "   - Verify hero section is visible"
echo "   - Verify no white/blank screen"
echo ""
echo "3. IMAGE LOADING TEST"
echo "   - Take snapshot"
echo "   - Count all img elements"
echo "   - Check network requests for 404 errors"
echo "   - Verify all images are .webp format"
echo ""
echo "4. CONSOLE ERRORS TEST"
echo "   - Read console messages"
echo "   - Filter for errors/exceptions"
echo "   - Report any JavaScript errors"
echo ""
echo "5. MOBILE RESPONSIVE TEST"
echo "   - Verify no horizontal scrollbar"
echo "   - Verify text is readable (min 14px)"
echo "   - Verify buttons are tappable (min 44px touch targets)"
echo ""
echo "6. ADD TO CART TEST"
echo "   - Find 'Add to Cart' button"
echo "   - Click button"
echo "   - Verify cart drawer/modal opens"
echo "   - Verify order bump checkbox is checked"
echo ""
echo "7. FAQ ACCORDION TEST"
echo "   - Find FAQ section"
echo "   - Click first question"
echo "   - Verify answer expands"
echo "   - Click again, verify collapses"
echo ""
echo "8. COMPARISON SECTION TEST"
echo "   - Scroll to 40% of page"
echo "   - Verify comparison section is visible"
echo "   - Verify before/after images load"
echo ""
echo "9. TIKTOK COMMENTS TEST"
echo "   - Return to hero section"
echo "   - Verify 3-5 TikTok comment overlays"
echo "   - Verify comments have content"
echo ""
echo "10. PERFORMANCE TEST"
echo "    - Start performance trace"
echo "    - Reload page"
echo "    - Stop trace"
echo "    - Report LCP, CLS, FID"
echo ""
echo "11. SIMPLESWAP FUNCTION TEST"
echo "    - Fetch: ${LIVE_URL}/.netlify/functions/buy-now"
echo "    - Verify returns JSON (not 404)"
echo "    - Verify function is operational"
echo ""
echo "12. ACCESSIBILITY TEST (a11y)"
echo "    - Run: bash tests/validate-accessibility.sh index.html"
echo "    - Or via browser:"
echo "    mcp__chrome-devtools__evaluate_script(function=\"() => {"
echo "      const issues = [];"
echo "      document.querySelectorAll('img').forEach(img => {"
echo "        if (!img.alt) issues.push('Missing alt: ' + img.src.slice(-30));"
echo "      });"
echo "      return { count: issues.length, issues: issues.slice(0,10) };"
echo "    }\")"
echo "    - Verify all images have alt text"
echo "    - Verify form inputs have labels"
echo "    - Verify heading hierarchy (1 h1)"
echo ""
echo "13. E2E ORDER FLOW TEST"
echo "    - Click primary CTA"
echo "    - Verify order bump pre-checked"
echo "    - Verify checkout initiates"
echo "    - Check for JavaScript errors"
echo "    - Run: bash tests/validate-e2e-order-flow.sh $LIVE_URL"
echo ""
echo "======================================"
echo "  EXPECTED PASS CRITERIA"
echo "======================================"
echo ""
echo "✅ Page loads < 5s"
echo "✅ Zero 404 image errors"
echo "✅ Zero console errors"
echo "✅ No horizontal scroll on mobile"
echo "✅ Add to Cart button works"
echo "✅ Order bump is pre-checked"
echo "✅ FAQ accordions work"
echo "✅ Comparison visible at 40% scroll"
echo "✅ TikTok comments visible in hero"
echo "✅ LCP < 2.5s"
echo "✅ CLS < 0.1"
echo "✅ SimpleSwap function returns 200"
echo "✅ Accessibility: all images have alt"
echo "✅ E2E: checkout flow works"
echo ""
echo "======================================"
echo "  SELF-HEALING"
echo "======================================"
echo ""
echo "If any test fails, run:"
echo "  bash tests/auto-fix.sh"
echo ""
echo "Then re-deploy and re-test."
echo ""
